### ISSUE TITLE
Copy results as query

### ISSUE THREAD

**Issue by jrcacd** [dive2Pro/roam-search-plus#15]

**Comment by dive2Pro** [comment]
query, what do you mean?

**Comment by jrcacd** [comment]
As a roam query ({{[[query]]: { ... }}})
So we can easy take the search results as a Roam query and put it on an page.

**Comment by dive2Pro** [comment]
In the next version, I'll bring a new feature: Inline Search. Does this fulfill your request? https://github.com/dive2Pro/roam-search-plus#inline-search

**Comment by jrcacd** [comment]
Excellent! It's really what we need!
