### ISSUE TITLE
[Feature Request] Use `Esc` to close the search panel

### ISSUE THREAD

**Issue by forrestchang** [dive2Pro/roam-search-plus#2]
## Problem

It is inconvenient to have to use the mouse to click elsewhere in order to close the search panel.

## Solution

A more convenient way to close the search panel is to use the keyboard shortcut Esc or Shift + Ctrl + P.

**Comment by dive2Pro** [comment]
hey, I think Shift+Ctrl+P already supports toggling the popup window , and "Esc" will be supported in next version

**Comment by forrestchang** [comment]
> hey, I think Shift+Ctrl+P already supports toggling the popup window , and "Esc" will be supported in next version

Oh, thanks. I tried `Shift+Ctrl+P`, but it seems to have some lag. I need to wait for 1 second and then can do some operations.

**Comment by dive2Pro** [comment]
Yes, i've noticed this problem too. The fix code is under review too, and hope the next update will solve your problem

**Comment by forrestchang** [comment]
New version works great!
